CollegeLife/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from Loginapp import views
from django.conf.urls.static import static
from django.conf import settings
from Issues.views import display


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^logout/$',views.user_logout,name='logout'),

    url(r'^special/',views.special, name='special'),
    url(r'^account/',include('Loginapp.urls')),
    url(r'^problem/',include('Issues.urls')),
    url(r'^display/', display , name='Display'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Issues/urls.py
from django.conf.urls import url
from . import views
#from . views import Upvote
app_name='Issues'
urlpatterns=[
	url(r'^$',views.problem,name='problem'),
	url(r'^active$',views.active,name='active'),
	url(r'^solved$',views.solved,name='solved'),
]

Loginapp/urls.py
from django.conf.urls import url
from Loginapp import views


app_name = 'Loginapp'


urlpatterns=[
	url(r'^register/$',views.register, name='register'),
	url(r'^user_login/$',views.user_login,name='user_login'),
	url(r'^$',views.account,name='account'),
	url(r'^college/$',views.college,name='college')

]

Issues/models.py
from django.db import models
from Loginapp.models import College, UserProfileInfo
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Problem(models.Model):
	prob_stat = models.TextField()
	created = models.DateField(default=date.today)

	college = models.ForeignKey(College, related_name='collegename' , null=True,blank=True,on_delete = models.CASCADE)
	count =models.IntegerField(blank=True, null=True)
	booltrue = models.BooleanField(default=False)

	def __str__(self):
		return self.prob_stat

Loginapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.


class College(models.Model):
	 college = models.CharField(max_length=200)

	 def __str__(self):
	 	return self.college

class UserProfileInfo(models.Model):

	#creating one to one relation with the admin model
	user=models.OneToOneField(User,on_delete=models.CASCADE )
	first_name = models.CharField(max_length=60, default='firstname', blank=False)
	last_name = models.CharField(max_length=60, default='lastname', blank=False)
	doc_image = models.ImageField(upload_to='documents', default='profile_pics/sumit.jpg', blank=False)
	college = models.ForeignKey(College, on_delete=models.CASCADE)
	mob_no = models.CharField(max_length=13, default='67567574', blank=False)
	dob = models.DateField( default=date.today, blank=False)
	profile_pic = models.ImageField(upload_to='profile_pics' ,blank=True)

	def __str__(self):

		return self.user.username

Issues/forms.py
from django import forms
from Issues.models import Problem

class ProblemForm(forms.ModelForm):
	prob_stat = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Problem'}))
	class Meta():
		model = Problem
		fields=('prob_stat',)

class UpvoteForm(forms.ModelForm):
	class Meta():
		model = Problem
		fields = ('booltrue',)

Loginapp/forms.py
from django import forms
from django.contrib.auth.models import User
from Loginapp.models import UserProfileInfo,College

class UserForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))
	class Meta():
		model = User
		fields = ('username', 'email', 'password')


class CollegeForm(forms.ModelForm):
	college = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'College'}))
	class Meta():
		model = College
		fields = '__all__'

class UserProfileInfoForm(forms.ModelForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}))
	mob_no = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Mobile No'}))
	#college = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'College Name'}))
	dob = forms.DateField(widget=forms.SelectDateWidget(years=[y for y in range(1930,2050)],attrs={'class':'form-control form-inline inline inlinef'}))
	doc_image = forms.FileField(widget=forms.FileInput(attrs={'class':'form-control','placeholder':'Document Image'}))
	profile_pic = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control','placeholder':'Profile Pic'}))
	class Meta():
		model= UserProfileInfo
		fields = ('first_name','last_name','mob_no','doc_image','college','dob','profile_pic')

Issues/views.py
from django.shortcuts import render
from .forms import ProblemForm,UpvoteForm
from .models import Problem
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from Loginapp.models import UserProfileInfo, College
from django.contrib.auth.models import User



# Create your views here.
@login_required
def problem(request):
	form = ProblemForm()

	prob = Problem()
	if request.method == 'POST':
		form = ProblemForm(request.POST)
		if form .is_valid():
			prob.college=UserProfileInfo.objects.filter(user=request.user)[0].college
			data = form.cleaned_data

			prob.prob_stat =data['prob_stat']
			prob.save()


			print(Problem.college)
			return HttpResponseRedirect("../../special")
		else:
			return HttpResponse("Error in form")
	return render(request,'Issues/Problem.html',{'form':form,})

def active(request):
	return render(request,'Issues/active.html')

def solved(request):
	return render(request,'Issues/solved.html')

def display(request):
	issue_list = Problem.objects.order_by('created')
	ucol = UserProfileInfo.objects.filter(user=request.user)[0].college
	return render(request,'Issues/display.html',{'display':issue_list,'college':ucol})

Loginapp/views.py
from django.shortcuts import render
from Loginapp.forms import UserProfileInfoForm, UserForm, CollegeForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login,logout,authenticate
from Loginapp.models import UserProfileInfo





# Create your views here.
def account(request):
	web_list = UserProfileInfo.objects.order_by('first_name')
	uid = request.user
	return render(request,'Loginapp/account.html',{
	'profile':web_list,
	'usern':uid,
	})

def index(request):
	return render(request,'Loginapp/index.html')

@login_required
def special(request):
	return HttpResponseRedirect('/display')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))


def college(request):
	form = CollegeForm()
	if request.method == 'POST':
		form =CollegeForm(request.POST)
		if form .is_valid():
			form.save()
			return HttpResponseRedirect('../register')
		else:
			return HttpResponse('OOPS Invalid Form')
	return render(request,'Loginapp/CollegeForm.html',{'form':form,})


def register(request):

	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(request.POST,request.FILES)

		if user_form.is_valid() and profile_form.is_valid() :

			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user
			profile.profile_pic = profile_form.cleaned_data['profile_pic']
			profile.doc_image = profile_form.cleaned_data['doc_image']
			profile.save()

			registered = True

		else:
			print(user_form.errors, profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request,'Loginapp/registeration.html',
		                   {'user_form':user_form,
		                    'profile_form':profile_form,
		                    'registered':registered,
							})



def user_login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect('/special/')

			else:
				return HttpResponse("Account Not Active")

		else:
			print("Someone tried to login and failed!")
			return HttpResponse("Invalid login details")

	else:
		return render(request,'Loginapp/login.html')

templates/Issues/Problem.html
{% extends 'Loginapp/base.html' %}
{% block body_block %}
<div class="container">
  <div class="row text-center p-5">
    <div class="col-md-12">
      <form method="POST">

      {% csrf_token %}
      <div class="form-group">
  		    {{ form.prob_stat }}
      </div>
  		<input class="btn btn-success form-control" type="submit" value="Submit">
      </form>
    </div>
    </div>
  </div>
</div>
{% endblock %}

templates/Issues/active.html
{% extends 'Loginapp/dashboard.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
      <h1 class="display-7">
        <a href="#"> NIT Raipur </a>
      </h1>
    </div>
    <div class="row">
      <h2 class="display-8">
        In time of girls?
      </h2>
    </div>
    <div class="row">
      <h2 class="display-8">
        <div class="btn-group">
        <kbd>Your Problem is in process of being resolved</kbd>
        </div>
      </h2>
    </div>
  <hr>
  <br>
{% endblock %}

templates/Issues/display.html
{% extends 'Loginapp/dashboard.html' %}
{% load staticfiles %}
{% block content %}
	{% for d in display %}
	{% if college == d.college %}
		<div class="container-fluid">
				<div class="row">
					<h1 class="display-7">
						<a href="#"> {{ d.college }} </a>
					</h1>
				</div>
				<div class="row">
					<h2 class="display-8">
						{{ d.prob_stat }}
					</h2>
				</div>
				<div class="row">
					<h2 class="display-8">
						<div class="btn-group">
						<a href="#" id="upvote" class="btn btn-success">Upvote | {{d.id}}</a>
						</div>
					</h2>
				</div>
			<hr>
			<br>
			<script
				  src="https://code.jquery.com/jquery-3.3.1.js"
				  crossorigin="anonymous"></script>
			<script src="{% static 'Issues/customjs.js' %}" charset="utf-8"></script>
		<link rel="stylesheet" href="{% static 'Loginapp/customstyle.css' %}">
		</div>
		{% endif %}
 	{% endfor %}
{% endblock %}

templates/Issues/solved.html
{% extends 'Loginapp/dashboard.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
      <h1 class="display-7">
        <a href="#"> NIT Raipur </a>
      </h1>
    </div>
    <div class="row">
      <h2 class="display-8">
        Mess Food
      </h2>
    </div>
    <div class="row">
      <h2 class="display-8">
        <div class="btn-group">
        <kbd>Your Problem is Solved</kbd>
        </div>
      </h2>
    </div>
  <hr>
  <br>
{% endblock %}

templates/Loginapp/account.html
{% extends 'Loginapp/dashboard.html' %}
{% block content %}
<div class="text-center p-5">
  {% for p in profile %}
    {% if p.user == usern %}
      <img class="rounded-circle" height="200px" width="200px" src='{{ p.profile_pic.url }}' alt="Profile Pic">
      <br><br>
      <h2 class="diplay-7">Welcome!</h1>
      <h1 class="display-5">
        <i>{{p.first_name}} {{p.last_name}}</i>.<br><br>
      </h1>
      <div class="container">
        <div class="row">
          <div class="col-md-3">
          </div>
      <div class="col-md-6">
      <table class="table">
          <tr >
          <td class="pad-max"> Mobile No   </td>
          <td> {{p.mob_no}} </td>
          </tr>
          <td> College </td>
          <td> {{p.college}} </td>
          <tr>

          </tr>
      </table>
    </div>
      <div class="col-md-3">
      </div>
    </div>
    </div>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

templates/Loginapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>CollegeMitra: A Perfect Companion</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
</head>
<body>
	<nav class="navbar bg-dark">
				<a class="btn btn-info" href="{% url 'index' %}">CollegeMitra</a>
				{% if user.is_authenticated %}
					<a class="btn btn-info" href="{% url 'Loginapp:account' %}">Goto Dashboard</a>
				{% else %}
				<div class="btn-group">
					<a class="btn btn-info" href="{% url 'Loginapp:register' %}">Register</a>
					<a class="btn btn-success" href="{% url 'Loginapp:user_login' %}">Login</a>
				</div>
				{% endif %}
		</nav>
	{% block body_block %}

	{% endblock %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/Loginapp/collegeform.html
{% extends 'Loginapp/base.html' %}
{% block body_block %}
<div class="container text-center">
  <div class="row p-5">
    <div class="col-md-2">
    </div>
		<div class="col-md-8">
			<h1 class="display-3 white-text">Add College</h1>
			<div class="well white-text">Now, It's time to put your college in our database</h1>
				<hr>
				<br>
			<form method="POST">
				{% csrf_token %}
				{{ form.college }}<br>
				<div class="form-group">
				<input class="btn btn-success form-control" type="submit" value="Submit" name="">
				</div>
			</form>
		</div>
		<div class="col-md-2">
		</div>
  </div>
</div>
{% endblock %}

templates/Loginapp/dashboard.html
{% extends "Loginapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1 class="display-3">CollegeMitra</h1>
  <p class="lead">Site Quotes</p>
</div>

<div class="container-fluid">
  <div class="row mar">
    <div class="col-md-2 bg-grey text-center p-5">
        <a  class="btn btn-success form-control" href="{% url 'Issues:problem' %}" class="btn btn-success">+Add</a>
        <br><br>
        <a  class="btn btn-info form-control" href="{% url 'special' %}">Dashboard</a><br>
        <br>
        <a  class="btn btn-info form-control" href="{% url 'Loginapp:account' %}">User details</a><br>
        <br>
        <a class="btn btn-drop form-control" data-toggle="collapse" data-target="#toggleprob">Problems</a>

        <div id="toggleprob" class="collapse">
          <a href="{% url 'Issues:active' %}"  class="btn btn-info form-control">Active</a><br>
          <a href="{% url 'Issues:solved' %}"  class="btn btn-info form-control">Solved</a>
        </div>
        <br><br>
        <a href="{% url 'logout' %}" class="btn btn-danger form-control">Logout</a>
    </div>
    <div class="col-md-10 bg-white">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>

<nav class="navbar bg-dark footer fixed-bottom">
  Copyright BadRushDeep &copy; Pvt. Ltd.
</nav>

{% endblock %}

templates/Loginapp/index.html
{% extends "Loginapp/base.html" %}
{% block body_block %}


<div class="jumbotron">
	<h1 class="display-4">Welcome To CollegeMitra</h1>
</div>
<br>
<h1 class="display-7 text-center p-3">"Stop talking about your problems,<br>and start thinking about your solutions.<br>Go ahead and post a problem to be solved."<br><br>-Admin</h1>
{% endblock %}

templates/Loginapp/login.html
{% extends 'Loginapp/base.html' %}

{% block body_block %}

<div class="jumbotron">
	<h1 class="display-4 text-center">Please Login</h1>
	<hr>
	<br>

	<div class="container">
		<div class="row">
			<div class="col-md-3">
			</div>
			<div class="col-md-6">
		<form action="{% url 'Loginapp:user_login' %}" method="post">
			{% csrf_token %}
			<div class="form-group">
			<input type="text" class="form-control" name="username" placeholder="Username">
			</div>
			<div class="form-group">
			<input type="password" class="form-control" name="password" placeholder="Password" >
			</div>
			<div class="form-group">
			<input type="submit" class="form-control btn btn-success" name="" value="Login">
			</div>
		</form>
		</div>
		<div class="col-md-3">
		</div>
	</div>
	</div>
</div>
{% endblock %}

templates/Loginapp/registeration.html
{% extends 'Loginapp/base.html' %}
{% load staticfiles %}


{% block body_block %}

<div class="jumbotron">
	{% if registered %}

	<h1>Thank you for registering!</h1>



	{% else %}

		<h1 class="text-center display-4">Register here!</h1>
		<h3 class="text-center display-6">Fill out the Form:</h3>
		<hr>
		<div class="container">
			<div class="row">
				<div class="col-md-3">
				</div>
				<div class="col-md-6">
		<form enctype="multipart/form-data" method="POST">
						{% csrf_token %}



			<div class="form-group">
					{{ user_form.username.errors }}
			  	{{ user_form.username}}
			</div>
			<div class="form-group">
					{{ user_form.email.errors }}
					{{ user_form.email}}
			</div>
			<div class="form-group">
					{{ user_form.password.errors }}
					{{ user_form.password}}
			</div>
			<!--Second Form-->
			<div class="form-group">
				{{ profile_form.first_name.errors }}
			{{ profile_form.first_name}}
			</div>
			<div class="form-group">
				{{ profile_form.last_name.errors }}
				{{ profile_form.last_name}}
			</div>
			<div class="form-group">
				{{ profile_form.password.errors }}
				{{ profile_form.password}}
			</div>
			<div class="form-group form-inline">
				{{ profile_form.dob.errors }}
				{{ profile_form.dob}}
			</div>
			Profile Picture:
			<br>
			<div class="form-group">
				{{ profile_form.profile_pic.errors }}
				{{ profile_form.profile_pic}}
			</div>
			College ID:
			<div class="form-group">
				{{ profile_form.doc_image.errors }}
				{{ profile_form.doc_image}}
			</div>
			<div class="form-group">
				{{ profile_form.mob_no.errors }}
				{{ profile_form.mob_no}}
			</div>
			<div class="form-group">
				{{ profile_form.college.errors }}
				{{ profile_form.college}}
				<a class="btn btn-sm btn-info" href="{% url 'Loginapp:college' %}">+Add College</a>
			</div>
			<input type="submit" class="btn btn-success form-control" value="Register">
			{% csrf_token %}
		</form>
	</div>
</div>
		{% endif %}

		{% endblock %}